### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kossanah** [frappe/paypal_integration#2]
I tried to install this app, on my VM and I am having errors. Please help
Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    init_site(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 154, in init_site
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 137, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 723, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 632, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).**file**), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 590, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
 ImportError: No module named Paypal

**Comment by jojouser** [comment]
I try to install this app, also have issue.
````
bench --site site1.local install-app paypal_integration
Installing paypal_integration...
Updating paypal_integration : [========================================]
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in runmodule_as_main
"main", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in runcode
exec code in run_globals
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in
main()
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
click.Group(commands=commands)(prog_name='bench')
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in call
return self.main(*args, **kwargs)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
return processresult(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
return callback(*args, **kwargs)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
installapp(app, verbose=context.verbose)
File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 126, in install_app
add_to_installed_apps(name)
File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 145, in add_to_installed_apps
post_install(rebuild_website)
File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 191, in post_install
init_singles()
File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 212, in init_singles
doc.save()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 231, in save
self.insert()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in insert
self.run_post_save_methods()
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 613, in run_post_save_methods
self.run_method("on_update")
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 557, in run_method
return Document.hook(fn)(self, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 712, in composer
return composed(self, method, *args, **kwargs)
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 695, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 551, in
fn = lambda self, args, **kwargs: getattr(self, method)(args, **kwargs)
File "/home/frappe/frappe-bench/apps/paypal_integration/paypal_integration/paypal_integration/doctype/paypal_settings/paypal_settings.py", line 13, in on_update
create_gateway_account()
File "/home/frappe/frappe-bench/apps/paypal_integration/paypal_integration/after_install.py", line 26, in create_gateway_account
if not bank.name:
AttributeError: 'NoneType' object has no attribute 'name'
````

**Comment by ghost** [comment]
Same Issue. Even on a reinstall. Fresh install on ubuntu 14
